/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155TokenEthSol from "./ERC1155TokenETH.sol";
export type { erc1155TokenEthSol };
import type * as erc1155TokenSkaleSol from "./ERC1155TokenSKALE.sol";
export type { erc1155TokenSkaleSol };
export type { ERC1155Token } from "./ERC1155Token";
