/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155TokenETH } from "./ERC1155TokenETH";
export type { MessageProxy } from "./MessageProxy";
