/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155TokenSKALE } from "./ERC1155TokenSKALE";
export type { MessageProxy } from "./MessageProxy";
