/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155TokenSKALE__factory } from "./ERC1155TokenSKALE__factory";
export { MessageProxy__factory } from "./MessageProxy__factory";
