/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc1155TokenEthSol from "./ERC1155TokenETH.sol";
export * as erc1155TokenSkaleSol from "./ERC1155TokenSKALE.sol";
export { ERC1155Token__factory } from "./ERC1155Token__factory";
